using System.Text;
using AmigaSharp.Runtime.Cpu;
using static AmigaSharp.Translator.InstructionEmitter;

namespace AmigaSharp.Translator;

/// <summary>
/// Writes a translated program as one C# class. Each function becomes a method. Each instruction becomes a block
/// with a comment that shows the source line.
/// </summary>
public sealed class CSharpProgramWriter
{
    private readonly ProgramAnalysis _analysis;
    private readonly StringBuilder _text = new();

    private CSharpProgramWriter(ProgramAnalysis analysis)
    {
        _analysis = analysis;
    }

    public static string Write(ProgramAnalysis analysis, string namespaceName, string className, string sourceName)
    {
        return new CSharpProgramWriter(analysis).WriteProgram(namespaceName, className, sourceName);
    }

    private string WriteProgram(string namespaceName, string className, string sourceName)
    {
        Line("// <auto-generated>");
        Line($"// AmigaSharp.Translator made this file from {sourceName}. Do not edit it.");
        Line("// </auto-generated>");
        Line("#pragma warning disable CS0162 // Unreachable code.");
        Line("#pragma warning disable CS0164 // A label is not used.");
        Line();
        Line("using AmigaSharp.Runtime;");
        Line("using AmigaSharp.Runtime.Cpu;");
        Line();
        Line($"namespace {namespaceName};");
        Line();
        Line($"public sealed class {className}(Core core) : TranslatedProgram(core)");
        Line("{");
        Line("    protected override void RegisterFunctions()");
        Line("    {");
        foreach (var function in _analysis.Functions.Values)
            Line($"        core.RegisterFunction({Hex(function.Start)}, {function.Name});");
        Line("    }");

        foreach (var function in _analysis.Functions.Values)
        {
            Line();
            WriteFunction(function);
        }

        Line("}");
        return _text.ToString();
    }

    private void WriteFunction(Function function)
    {
        var flow = new ProgramFlow(_analysis, function);
        var emitter = new InstructionEmitter(flow);

        // Emit the code first. This finds the labels that the code jumps to.
        var bodies = new List<(CodeInstruction Code, List<string> Lines)>();
        for (var n = 0; n < function.Instructions.Count; n++)
        {
            var code = function.Instructions[n];
            var instruction = code.Instruction;
            var lines = emitter.Emit(instruction);

            // If the code continues to an address that is not the next instruction in this method, jump there.
            var next = instruction.NextAddress;
            var hasNext = n + 1 < function.Instructions.Count && function.Instructions[n + 1].Instruction.Address == next;
            if (!EndsFlow(instruction) && !hasNext)
                lines.Add(flow.Jump(instruction, next));
            bodies.Add((code, lines));
        }

        WriteFunctionComment(function);
        Line($"    public void {function.Name}()");
        Line("    {");
        foreach (var (code, lines) in bodies)
        {
            var address = code.Instruction.Address;
            foreach (var comment in SourceComments(code, isFunctionStart: address == function.Start))
                Line($"        {comment}");
            if (flow.Labels.Contains(address))
                Line($"    L_{address:X6}:");
            Line("        {");
            foreach (var line in lines)
                Line($"            {line}");
            Line("        }");
        }

        Line("    }");
    }

    private void WriteFunctionComment(Function function)
    {
        var first = function.Instructions.FirstOrDefault()?.Line;
        var location = first == null ? "" : $" ({first.File}:{first.LineNumber})";
        Line($"    // ${function.Start:X6}{location}");
    }

    private IEnumerable<string> SourceComments(CodeInstruction code, bool isFunctionStart)
    {
        var instruction = code.Instruction;
        var line = code.Line;
        if (line != null && code.FirstOfLine)
        {
            var (hunk, offset) = _analysis.HunkOffset(instruction.Address);
            foreach (var label in _analysis.Listing!.LabelsAt(hunk, offset))
            {
                if (!isFunctionStart || label.StartsWith('.'))
                    yield return $"// {label}:";
            }

            if (line.MacroCall != null)
            {
                yield return $"// {line.File}:{line.LineNumber}: {line.MacroCall.Trim()}";
                yield return $"//   (macro) {line.Source.Trim()}";
            }
            else
            {
                yield return $"// {line.File}:{line.LineNumber}: {line.Source.Trim()}";
            }
        }

        yield return $"// ${instruction.Address:X6}  {instruction}";
    }

    private void Line(string text = "")
    {
        _text.Append(text).Append('\n');
    }

    /// <summary>The control flow of a translated function.</summary>
    private sealed class ProgramFlow(ProgramAnalysis analysis, Function function) : IControlFlow
    {
        /// <summary>The addresses in this function that the code jumps to.</summary>
        public HashSet<uint> Labels { get; } = [];

        public string Jump(Instruction instruction, uint target)
        {
            // A backward jump can be a loop that waits for an interrupt, so it is a safe point for interrupts.
            var poll = target <= instruction.Address ? "core.Poll(); " : "";
            if (function.Contains(target) && analysis.IsInstruction(target))
            {
                Labels.Add(target);
                return poll.Length == 0 ? $"goto L_{target:X6};" : $"{{ {poll}goto L_{target:X6}; }}";
            }

            // A jump to the start of another function is a tail call.
            return analysis.FunctionAt(target) is { } other
                ? $"{{ {poll}{other.Name}(); return; }}"
                : $"{{ {poll}core.Dispatch({Hex(target)}); return; }}";
        }

        public string JumpDynamic(Instruction instruction, string target) => $"{{ core.Dispatch({target}); return; }}";

        public string Call(Instruction instruction, uint target)
        {
            var returnAddress = Hex(instruction.NextAddress);
            return analysis.FunctionAt(target) is { } other
                ? $"core.Call({returnAddress}, {other.Name});"
                : $"core.CallAddress({returnAddress}, {Hex(target)});";
        }

        public string CallDynamic(Instruction instruction, string target) =>
            $"core.CallAddress({Hex(instruction.NextAddress)}, {target});";

        public string Return(Instruction instruction, string address) => $"{{ core.ReturnTo({address}); return; }}";
    }
}
