<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\AmigaSharp.Runtime\AmigaSharp.Runtime.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latestmajor</LangVersion>
        <RootNamespace>AmigaSharp</RootNamespace>
    </PropertyGroup>

</Project>
